services:
  - type: web
    name: stacksgate-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "https://stacksgate-frontend-gold.vercel.app,https://stacks-gate-frontend.vercel.app,https://stacksgate.vercel.app"